client_id = "32c1c3d388a14e4981d80295af909be7"
theme = "Tokyonight-storm"
enable_media_control = true
enable_cover_image_cache = true
page_size_in_rows = 50
track_table_item_max_len = 50
pause_icon = "⏸"
liked_icon = "♥"
play_icon = "▶️"
border_type	 = "Rounded"
playback_window_position = "Bottom"
cover_img_width = 5
cover_img_length = 11


[device]
volume = 100
audio_cache = true
bitrate = 320