client_id = "32c1c3d388a14e4981d80295af909be7"
theme = "Tokyo-Night-Storm"
enable_media_control = true
page_size_in_rows = 50
track_table_item_max_len = 50
pause_icon = "â¸ï¸"
liked_icon = "ğŸ’™"
play_icon = "â–¶ï¸"
border_type	 = "Hidden"
playback_window_position = "Bottom"
cover_img_width = 4


[device]
volume = 80
audio_cache = true
bitrate = 320